name: test_task1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  collection: ^1.19.1
  #Stroring and data processing
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  #Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  #Annotations
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.13
  #Codegen
  freezed: ^3.2.4
  build_runner: ^2.10.5
  json_serializable: ^6.11.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
